In [2]:
import numpy as np
from scipy import stats


marks = np.array([45, 67, 89, 90, 56, 78, 88, 92, 61, 74,
                  83, 95, 52, 68, 71, 85, 77, 64, 58, 81])

In [3]:
# 1. Mean
print("1. Mean:", np.mean(marks))

1. Mean: 73.7


In [10]:
# 2. Median
print("Median:", np.median(marks))

Median: 75.5


In [11]:
# 3. Mode
values, counts = np.unique(marks, return_counts=True)
max_count = np.max(counts)

if max_count == 1:
    print(" Mode: No mode found")
else:
    mode = values[counts == max_count]
    print("Mode:", mode)


 Mode: No mode found


In [12]:
# 4. Maximum and Minimum
print(" Maximum:", np.max(marks))
print("  Minimum:", np.min(marks))

 Maximum: 95
  Minimum: 45


In [13]:
# 5. Range
print("5. Range:", np.max(marks) - np.min(marks))

5. Range: 50


In [14]:
# 6. Variance
print("6. Variance:", np.var(marks))

6. Variance: 199.21


In [15]:

# 7. Standard Deviation
print("7. Standard Deviation:", np.std(marks))

7. Standard Deviation: 14.114177269681715


In [16]:
# 8. First Quartile 
q1 = np.percentile(marks, 25)
print("8. Q1 (25th Percentile):", q1)


8. Q1 (25th Percentile): 63.25


In [17]:
# 9. Second Quartile (Q2)
q2 = np.percentile(marks, 50)
print("9. Q2 (50th Percentile):", q2)

9. Q2 (50th Percentile): 75.5


In [18]:
# 10. Third Quartile (Q3)
q3 = np.percentile(marks, 75)
print("10. Q3 (75th Percentile):", q3)


10. Q3 (75th Percentile): 85.75


In [19]:
# 11. Interquartile Range (IQR)
iqr = q3 - q1
print("11. IQR:", iqr)

11. IQR: 22.5


In [20]:
# 12. Students Above Mean
mean = np.mean(marks)
print("12. Students Above Mean:", np.sum(marks > mean))

12. Students Above Mean: 11


In [21]:
# 13. Students Below 60
print("13. Students Below 60:", np.sum(marks < 60))

13. Students Below 60: 4


In [22]:
# 14. Sum and Manual Average
total = np.sum(marks)
average = total / len(marks)

print("14. Sum of Marks:", total)
print("    Manual Average:", average)

14. Sum of Marks: 1474
    Manual Average: 73.7


In [23]:
# 15. Sorting
ascending = np.sort(marks)
descending = ascending[::-1]

print("15. Ascending Order:")
print(ascending)

print("    Descending Order:")
print(descending)

print("    Top 5 Highest Scores:")
print(descending[:5])

15. Ascending Order:
[45 52 56 58 61 64 67 68 71 74 77 78 81 83 85 88 89 90 92 95]
    Descending Order:
[95 92 90 89 88 85 83 81 78 77 74 71 68 67 64 61 58 56 52 45]
    Top 5 Highest Scores:
[95 92 90 89 88]
