In [2]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a+b

array([[ 6,  8],
       [10, 12]])

In [6]:
a*b

array([[ 5, 12],
       [21, 32]])

In [4]:
a**b

array([[    1,    64],
       [ 2187, 65536]])

In [5]:
# matrix multiplication
print(np.matmul(a,b))

[[19 22]
 [43 50]]


In [8]:
# transpose 
print(a.T)

[[1 3]
 [2 4]]


In [11]:
# inverse of a square matrix.
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [13]:
# determinant
print(np.linalg.det(a))


-2.0000000000000004


PRACTICE QUESTION

In [14]:
import numpy as np

# Matrix A
A = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
])

# Matrix B
B = np.array([
    [1, 3, 5],
    [7, 9, 11],
    [13, 15, 17]
])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix B:
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [32]:
# 1. Find the shape, size and dimensions of both matrices.
print(np.shape(A))
print(np.shape(B))

print(np.size(A))
print(np.size(B))


print(A.ndim)
print(B.ndim)

(3, 3)
(3, 3)
9
9
2
2


In [19]:
# 2. Perform element-wise addition of A and B.
A+B

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [20]:
# 3. Perform element-wise subtraction (A - B).
A-B

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
# 4. Perform element-wise multiplication.
A*B

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [22]:
# 5. Perform matrix multiplication using np.matmul().
print(np.matmul(A, B))

[[108 132 156]
 [234 294 354]
 [360 456 552]]


In [24]:
# 6. Find the transpose of both matrices.
print(A.T)

[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]


In [25]:
# 7. Find the determinant of matrix A.
print(np.linalg.det(A))

5.329070518200782e-15


In [ ]:
# 8. Find the inverse of matrix A (if possible).
if np.linalg.det(A) != 0:
    print(np.linalg.inv(A))
else:
    print("Inverse does not exist (Singular Matrix)")

In [37]:
# 9. Find the trace (sum of diagonal elements) of both matrices.
print(np.trace(A))
print(np.trace(B))


30
27


In [35]:
# 10. Find the maximum, minimum, mean and sum of matrix A.
print(np.max(A))
print(np.min(A))
print(np.mean(A))
print(np.sum(A))

18
2
10.0
90


In [36]:
# 11. Find the row-wise sum and column-wise sum of matrix B.
print(np.sum(B, axis=1))   # Row-wise

print(np.sum(B, axis=0))   # Column-wise

[ 9 27 45]
[21 27 33]


In [ ]:
# 12. Extract:
# a) First row
print(A[0])

# b) Second column
print(A[:, 1])

# c) Last row
print(A[-1])

# d) Bottom-right element
print(A[-1, -1])

In [ ]:
# 13. Reshape matrix A into a (1,9) array and flatten matrix B.
print(A.reshape(1, 9))

print(B.flatten())

In [ ]:
# 14. Find the eigenvalues and eigenvectors of matrix A.
values, vectors = np.linalg.eig(A)

print(values)
print(vectors)


In [ ]:
# 15. Concatenate A and B:
#     a) Horizontally (hstack)
#     b) Vertically (vstack)

